---
# Source: application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-application
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::308190735829:role/blend-clinch-dev-role
---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-application
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-application
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        timestamp: "2025-02-05T09:34:33"
      labels:
        app.kubernetes.io/name: application
        app.kubernetes.io/instance: release-name
    spec:
      imagePullSecrets:
        - name: application
      serviceAccountName: release-name-application
      initContainers:
      - name: db-migrations
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database_url
              name: clinch-postgres-url
      containers:
        - name: application
          image: "docker.io/radixdlt/application:1.0.0"
          imagePullPolicy: Always
          env:
          - name: AWS_SES_SENDER
            value: "no-reply-blend-dev@rdx-works-main.extratools.works"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: clinch-postgres-url
                key: database_url
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: clinch-auth-secret
                key: auth_secret
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-application
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.rdx-works-main.extratools.works/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.rdx-works-main.extratools.works/oauth2/auth
spec:
  ingressClassName: nginx
  rules:
    - host: "dev-blend-clinch.rdx-works-main.extratools.works"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-application
                port:
                  number: 80
---
# Source: application/templates/docker-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of ExternalSecret under CRD section
  name: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    # name of actual secret under Config/Secrets, not required will use .metadata.name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: docker.io/radixdlt
      version: "AWSCURRENT"
      property: dockerconfigjson
---
# Source: application/templates/secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinch-postgres-url
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: database_url
      remoteRef:
        key: rdx-works-main-dev/eks/blend/dev/secrets
        property: database_url
---
# Source: application/templates/secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinch-auth-secret
  labels:
    helm.sh/chart: application-1.0.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: auth_secret
      remoteRef:
        key: rdx-works-main-dev/eks/blend/dev/secrets
        property: auth_secret
