---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
