---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: proprietary
  namespace: helm-repos
spec:
  interval: 180m
  url: https://github.com/duje-begonja-rdx/flux
  ref:
    branch: main
---