apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/
  - ./traefik.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kps
      namespace: monitoring
    path: ./patch-prometheus.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: loki
      namespace: logs
    path: ./patch-loki.yaml
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: alloy
      namespace: logs
    path: ./patch-alloy.yaml
