---
apiVersion: v1
kind: Namespace
metadata:
  name: route-counter-dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: route-counter
  namespace: route-counter-dev
spec:
  releaseName: route-counter
  # How often Flux reconciles this HelmRelease and checks whether it should apply changes.
  interval: 20m
  targetNamespace: route-counter-dev
  chart:
    spec:
      # How often Flux checks the chart source reference for updated chart content.
      interval: 20m
      chart: ./charts/common
      sourceRef:
        kind: GitRepository
        name: proprietary
        namespace: helm-repos
  values:
    nameOverride: "route-counter"
    image:
      repository: docker.io/kagunda/python-endpoint-counter
      pullPolicy: Always
      tag: "v1.0.0"
    docker_secret:
      enabled: false
    replicaCount: 1
    params:
      FLASK_PORT: "5000"
    ports:
      - containerPort: 5000
        name: http
        protocol: TCP
    serviceAccount:
      create: true
      name: "route-counter-dev"
    resources:
      requests:
        memory: 128Mi
        cpu: 25m
    service:
      ports:
        - port: 80
          name: http
          protocol: TCP
          targetPort: http
      type: ClusterIP
    ingress:
      enabled: true
      basic_auth: false
      className: "traefik"
      hosts:
        - host: dev-route-counter.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: 80
