---
apiVersion: v1
kind: Namespace
metadata:
  name: ethereum-sepolia
---
apiVersion: v1
kind: Secret
metadata:
  name: eth-jwt
  namespace: ethereum-sepolia
type: Opaque
stringData:
  jwt.hex: "5dd19aa4d37f907a32ebc12f90e4e845a4566198e712faf6972e1df369fea7e5"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eth-geth
  namespace: ethereum-sepolia
spec:
  releaseName: eth-geth
  interval: 20m
  targetNamespace: ethereum-sepolia
  chart:
    spec:
      reconcileStrategy: Revision
      interval: 20m
      chart: ./charts/ethereum-component
      valuesFiles:
        - charts/ethereum-component/geth-values.yaml
      sourceRef:
        kind: GitRepository
        name: proprietary
        namespace: helm-repos
  values:
    nameOverride: "eth-geth"
    params:
      GETH_SEPOLIA: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eth-prysm
  namespace: ethereum-sepolia
spec:
  releaseName: eth-prysm
  interval: 20m
  targetNamespace: ethereum-sepolia
  chart:
    spec:
      reconcileStrategy: Revision
      interval: 20m
      chart: ./charts/ethereum-component
      valuesFiles:
        - charts/ethereum-component/prysm-values.yaml
      sourceRef:
        kind: GitRepository
        name: proprietary
        namespace: helm-repos
  values:
    nameOverride: "eth-prysm"
