---
apiVersion: v1
kind: Namespace
metadata:
  name: ethereum-ephemery
---
apiVersion: v1
kind: Secret
metadata:
  name: eth-jwt
  namespace: ethereum-ephemery
type: Opaque
stringData:
  jwt.hex: "5dd19aa4d37f907a32ebc12f90e4e845a4566198e712faf6972e1df369fea7e5"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eth-geth
  namespace: ethereum-ephemery
spec:
  releaseName: eth-geth
  interval: 20m
  targetNamespace: ethereum-ephemery
  chart:
    spec:
      reconcileStrategy: Revision
      interval: 20m
      chart: ./charts/ethereum-component
      valuesFiles:
        - geth-values.yaml
      sourceRef:
        kind: GitRepository
        name: proprietary
        namespace: helm-repos
  values:
    nameOverride: "eth-geth"
    params:
      GETH_EPHEMERY: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eth-lighthouse
  namespace: ethereum-ephemery
spec:
  releaseName: eth-lighthouse
  interval: 20m
  targetNamespace: ethereum-ephemery
  chart:
    spec:
      reconcileStrategy: Revision
      interval: 20m
      chart: ./charts/ethereum-component
      valuesFiles:
        - lighthouse-values.yaml
      sourceRef:
        kind: GitRepository
        name: proprietary
        namespace: helm-repos
  values:
    nameOverride: "eth-lighthouse"
